# Generated by Django 4.0.3 on 2023-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_remove_automobilevo_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
