# Generated by Django 4.0.3 on 2023-01-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecordVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vip_status',
            field=models.BooleanField(default=False),
        ),
    ]
