# Generated by Django 4.0.3 on 2023-01-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_serviceappointment_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
