# Generated by Django 4.0.3 on 2023-01-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_serviceappointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
