# Generated by Django 4.0.3 on 2023-06-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_serviceappointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
